import { readdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { createCdpClient, waitForDefaultExecutionContext } from "./godot-web-cdp";

// Reports are generated by the real native-backed TraceIntegrationTests, not hand-authored stand-ins.
const root = resolve(process.argv[2] ?? "artifacts/integration-browser");
const port = Number(process.argv[3] ?? "9228");
const files = (await readdir(root)).filter(f => f.endsWith(".html"));
for (const outcome of ["passed", "failed", "interrupted"])
  if (!files.some(f => f.startsWith(outcome + "-"))) throw new Error("Missing real integration report: " + outcome);
const endpoint = `http://127.0.0.1:${port}`;
const target = await (await fetch(endpoint + "/json/new?about:blank", { method: "PUT" })).json() as { id: string; webSocketDebuggerUrl: string };
const client = createCdpClient(target.webSocketDebuggerUrl);
await client.open();
const monitor = new WebSocket(target.webSocketDebuggerUrl);
await new Promise<void>((done, fail) => { monitor.addEventListener("open", () => done(), { once: true }); monitor.addEventListener("error", fail, { once: true }); });
const external: string[] = [], exceptions: string[] = [];
monitor.addEventListener("message", e => {
  const m = JSON.parse(String(e.data));
  if (m.method === "Network.requestWillBeSent" && /^(https?:|file:)/.test(m.params.request.url) && !m.params.request.url.startsWith(pathToFileURL(root + "/").href)) external.push(m.params.request.url);
  if (m.method === "Runtime.exceptionThrown") exceptions.push(m.params.exceptionDetails.text + " " + (m.params.exceptionDetails.exception?.description ?? ""));
  if (m.method === "Page.javascriptDialogOpening") exceptions.push("unexpected dialog");
});
async function enableMonitoring(method: string, id: number) {
  await new Promise<void>((done, fail) => {
    const timer = setTimeout(() => { monitor.removeEventListener("message", reply); fail(new Error("Monitor activation timed out: " + method)); }, 10000);
    function reply(e: MessageEvent) {
      const m = JSON.parse(String(e.data));
      if (m.id !== id) return;
      clearTimeout(timer); monitor.removeEventListener("message", reply);
      if (m.error) fail(new Error("Monitor activation failed: " + method + " " + m.error.message));
      else done();
    }
    monitor.addEventListener("message", reply);
    monitor.send(JSON.stringify({ id, method }));
  });
}
// Responses on this monitoring connection must arrive before navigation on the command connection.
for (const [i, method] of ["Network.enable", "Runtime.enable", "Page.enable"].entries()) await enableMonitoring(method, i + 1);
async function evaluate(expression: string) {
  const result = await client.send("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true }) as { result?: { value?: any }; exceptionDetails?: unknown };
  if (result.exceptionDetails) throw new Error("Browser evaluation failed: " + JSON.stringify(result.exceptionDetails));
  return result.result?.value;
}
function require(value: unknown, reason: string) { if (!value) throw new Error(reason); }
async function wait(expression: string) {
  const deadline = performance.now() + 10000;
  while (performance.now() < deadline) { if (await evaluate(expression)) return; await Bun.sleep(50); }
  throw new Error("Browser condition timed out: " + expression);
}
const evidence: object[] = [];
try {
  // Prove the monitor sees startup-time faults before using an empty array as safety evidence.
  const probeUrl = endpoint + "/monitor-self-test";
  const probeHtml = `<script>const img=new Image();img.src=${JSON.stringify(probeUrl)};throw new Error('MONITOR-FIXTURE-FAILURE');</script>`;
  await client.send("Page.navigate", { url: "data:text/html," + encodeURIComponent(probeHtml) });
  const probeDeadline = performance.now() + 10000;
  while (performance.now() < probeDeadline &&
      !(external.includes(probeUrl) && exceptions.some(e => e.includes("MONITOR-FIXTURE-FAILURE")))) await Bun.sleep(50);
  require(external.includes(probeUrl), "Monitor did not observe the deliberate startup request");
  require(exceptions.some(e => e.includes("MONITOR-FIXTURE-FAILURE")), "Monitor did not observe the deliberate startup exception");
  const monitorProbe = { startupRequestObserved: true, startupExceptionObserved: true };
  external.length = 0; exceptions.length = 0;
  await client.send("Emulation.setDeviceMetricsOverride", { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false });
  for (const file of files) {
    const outcome = file.split("-")[0]!;
    const url = pathToFileURL(resolve(root, file)).href;
    await client.send("Page.navigate", { url });
    await waitForDefaultExecutionContext(client, 10000, url);
    await wait("!!document.querySelector('.gua-trace')");
    await evaluate("document.querySelectorAll('details').forEach(d=>d.open=true)");
    const text = await evaluate("document.body.innerText") as string;
    require(text.includes("Primary result: " + outcome), "primary result " + file);
    for (const schema of ["gua.semantic-lint.v1", "gua.semantic-comparison.v1", "gua.trace.recording.v1", "gua.recording.references.v1", "gua.diagnostics.v1", "gua.environment.v1"])
      require(text.includes(schema), "missing real attachment " + schema);
    require(text.includes('"matched": true') && text.includes('"baselineUpdated": false'), "explicit comparison and no automatic update");
    require(text.includes("Assertion truth: true") && text.includes("caller execution result: " + outcome), "truth separate from caller result");
    require(text.includes("Intermediate change: changed") && text.includes("before → main-result"), "intermediate Observe and geometry difference");
    require(text.includes("pendingRequests") && text.includes("safe-log"), "real pending/log diagnostics");
    require(!text.includes("SECRET-MARKER") && !text.includes('"baselinePath"') && !text.includes('"artifactPath"'), "redaction and path omission");
    require(await evaluate("!window.__hostileExecuted && !document.querySelector('img[src^=http],a[href^=http]')"), "inert hostile attachment");
    await evaluate("document.querySelectorAll('article details').forEach(d=>d.open=false)");
    const shot = await client.send("Page.captureScreenshot", { format: "png" }) as { data: string };
    await writeFile(resolve(root, file + ".png"), Buffer.from(shot.data, "base64"));
    await evaluate("[...document.querySelectorAll('nav button')].find(b=>b.textContent.includes('Caller cleanup')).click()");
    await wait("document.querySelector('article').innerText.includes('Caller cleanup')");
    require(await evaluate(`document.body.innerText.includes('Primary result: ${outcome}') && document.querySelector('article').innerText.includes('Step result: passed')`), "cleanup independent of primary");
    evidence.push({ file, outcome, checks: "real lint/comparison/Recording/diagnostics/environment, truth, geometry, intermediate Observe, redaction, inert attachments, cleanup" });
  }
  require(external.length === 0, "external reads: " + external.join(","));
  require(exceptions.length === 0, "browser exceptions: " + exceptions.join(","));
  const browser = await (await fetch(endpoint + "/json/version")).json();
  await writeFile(resolve(root, "browser-evidence.json"), JSON.stringify({ browser: browser.Browser, monitorProbe, evidence, external, exceptions }, null, 2));
  console.log(JSON.stringify({ passed: evidence.length, external, exceptions }));
} finally { monitor.close(); client.close(); await fetch(endpoint + "/json/close/" + target.id); }
